backend:
  name: git-gateway
  repo: JakubSimoncic/web
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "footer"
    label: "Bagety – Footer"
    files:
      - label: "Footer sekce (Bagety)"
        name: "footer_bagety"
        file: "bistro/public/web/BAGETY.html"
        fields:
          - label: "Text ve footeru"
            name: "footer_text"
            widget: "markdown"
