collections:
  - name: "footer-sekce-bagety"
    label: "Footer sekce BAGETY"
    files:
      - label: "Footer BAGETY"
        name: "footer_bagety"
        file: "bistro/public/web/BAGETY.html"
        fields:
          - label: "Text v patičce"
            name: "footer_text"
            widget: "markdown"
