backend:
  name: git-gateway
  repo: JakubSimoncic/bistro-cms
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Stránky"
    files:
      - label: "Bagety"
        name: "bagety"
        file: "content/BAGETY.md"
        fields:
          - { label: "Text", name: "text", widget: "markdown" }

      - label: "Chlebíčky"
        name: "chlebicky"
        file: "content/CHLEBICKY.md"
        fields:
          - { label: "Titulek", name: "title", widget: "string", required: true }
          - { label: "Text", name: "text", widget: "markdown" }

      - label: "Galerie"
        name: "galerie"
        file: "content/GALERIE.md"
        fields:
          - { label: "Titulek", name: "title", widget: "string", required: true }
          - { label: "Obrázky", name: "images", widget: "list", fields: [{ label: "Obrázek", name: "image", widget: "image" }] }
          - { label: "Popis", name: "description", widget: "markdown" }
          - { label: "Text", name: "text", widget: "markdown" }

      - label: "Kontakt"
        name: "kontakt"
        file: "content/KONTAKT.md"
        fields:
          - { label: "Titulek", name: "title", widget: "string", required: true }
          - { label: "Adresa", name: "address", widget: "string" }
          - { label: "Telefon", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Text", name: "text", widget: "markdown" }

      - label: "Menu"
        name: "menu"
        file: "content/MENU.md"
        fields:
          - { label: "Titulek", name: "title", widget: "string", required: true }
          - { label: "Text", name: "text", widget: "markdown" }

      - label: "Nápoje"
        name: "napoje"
        file: "content/NAPOJE.md"
        fields:
          - { label: "Titulek", name: "title", widget: "string", required: true }
          - { label: "Text", name: "text", widget: "markdown" }

      - label: "Naše nabídka"
        name: "nase_nabidka"
        file: "content/NASE_NABIDKA.md"
        fields:
          - { label: "Titulek", name: "title", widget: "string", required: true }
          - { label: "Text", name: "text", widget: "markdown" }

      - label: "O nás"
        name: "o_nas"
        file: "content/O_NAS.md"
        fields:
          - { label: "Titulek", name: "title", widget: "string", required: true }
          - { label: "Text", name: "text", widget: "markdown" }

      - label: "Pečivo"
        name: "pecivo"
        file: "content/PECIVO.md"
        fields:
          - { label: "Titulek", name: "title", widget: "string", required: true }
          - { label: "Text", name: "text", widget: "markdown" }

      - label: "Pomazánky"
        name: "pomazanky"
        file: "content/POMAZANKY.md"
        fields:
          - { label: "Titulek", name: "title", widget: "string", required: true }
          - { label: "Text", name: "text", widget: "markdown" }

      - label: "Hlavní stránka"
        name: "index"
        file: "content/index.md"
        fields:
          - { label: "Titulek", name: "title", widget: "string", required: true }
          - { label: "Text", name: "text", widget: "markdown" }
