backend:
  name: git-gateway
  repo: JakubSimoncic/web
  branch: main

media_folder: "bistro/public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Stránky"
    folder: "bistro/public/content"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - label: "Titulek"
        name: "title"
        widget: "string"
      - label: "Text"
        name: "text"
        widget: "markdown"
  - name: "bagety_page"
    label: "Obsah Baget"
    files:
      - file: "bistro/public/content/BAGETY.md"
        label: "Hlavní obsah"
        name: "main_content"
        fields:
          - label: "Titulek"
            name: "title"
            widget: "string"
          - label: "Obsah"
            name: "text"
            widget: "markdown" # ZPĚT NA markdown
