collections:
  - name: "bagety"
    label: "Bagety"
    folder: "bistro/public/web"
    create: true
    slug: "{{slug}}"
    extension: "html"
    fields:
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "text", name: "text", widget: "markdown" }
