backend:
  name: git-gateway
  branch: main

media_folder: "web"
public_folder: "/web"

media_library:
  name: uploadcare
  config:
    publicKey: demo

    
collections:
  - name: "menu"
    label: "Denní menu"
    create: false
    files:
      - file: "web/pages/2025-07-29.md"
        label: "Denní menu 29.7.2025"
        name: "denni_menu_2025_07_29"
        fields:
          - { label: "Titulek", name: "title", widget: "string" }
          - { label: "Datum", name: "date", widget: "datetime" }
          - { label: "Obsah", name: "body", widget: "markdown" }

