backend:
  name: git-gateway
  branch: main

media_folder: "web/uploads"
public_folder: "/web/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: demo

collections:
  - name: "menu"
    label: "Denní menu"
    folder: "web/pages"
    create: true
    slug: "{{year}}-{{month}}-{{day}}"
    fields:
      - { label: "Titulek", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Obsah", name: "body", widget: "markdown" }
