backend:
  name: git-gateway
  repo: JakubSimoncic/web
  branch: main

media_folder: "bistro/public/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Stránky"
    folder: "bistro/public/content"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - label: "Titulek"
        name: "title"
        widget: "string"
      - label: "Text"
        name: "text"
        widget: "markdown"
