backend:
  name: git-gateway
  repo: JakubSimoncic/web
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "footer-sekce-bagety"
    label: "Footer sekce BAGETY"
    files:
      - label: "Footer BAGETY"
        name: "footer"
        file: "bistro/public/web/BAGETY.html"
        fields:
          - label: "Text v patičce"
            name: "footer_text"
            widget: "markdown"
