backend:
  name: git-gateway
  branch: main

media_folder: "web"
public_folder: "/web"

media_library:
  name: uploadcare
  config:
    publicKey: demo

    
collections:
  - name: "menu"
    label: "Denní menu"
    create: false
    files:
      - file: "bistro/public/web/pages/denni-menu.md"
        label: "Denní menu CZ"
        name: "denni_menu_2025_07_29"
        fields:
          - { label: "Titulek", name: "title", widget: "string" }
          - { label: "Obsah", name: "body", widget: "markdown" }

      - file: "bistro/public/web/pages/menu-en.md"
        label: "Denní menu EN"
        name: "denni_menu_en"
        fields:
          - { label: "Titulek", name: "title", widget: "string" }
          - { label: "Obsah", name: "body", widget: "markdown" }
